/**
 * TopicPage Component
 *
 * Lightweight wrapper for a single topic with stable positional key.
 * Receives topicId and category as PROPS (not derived from key).
 * The parent (SimpleTopicPager) sets stable positional keys that NEVER change.
 *
 * Features:
 * - Fetches topic content using useTopicById and useTopicReferences hooks
 * - Shows SkeletonLoader while loading
 * - Renders topic content when loaded (Bible references or Explanations)
 * - Contains ScrollView for vertical scrolling
 * - Props update when window shifts (key stays stable)
 * - Handles scroll velocity calculation for FAB visibility
 * - Handles tap detection for FAB toggle
 *
 * @see Spec: agent-os/specs/2025-12-08-topic-swipe-navigation/spec.md
 */

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { GestureResponderEvent, NativeScrollEvent, NativeSyntheticEvent } from 'react-native';
import { FlatList, InteractionManager, ScrollView, StyleSheet, Text, View } from 'react-native';
import type { RenderRules } from 'react-native-markdown-display';
import Markdown from 'react-native-markdown-display';
import Animated, {
  Easing,
  type SharedValue,
  useAnimatedStyle,
  useSharedValue,
  withTiming,
} from 'react-native-reanimated';
import { BottomLogo } from '@/components/bible/BottomLogo';
import { HighlightedText, type WordSelection } from '@/components/bible/HighlightedText';
import { ShareButton } from '@/components/bible/ShareButton';
import { SkeletonLoader } from '@/components/bible/SkeletonLoader';
import { WordDefinitionTooltip } from '@/components/bible/WordDefinitionTooltip';
import { TopicText, type VersePress } from '@/components/topics/TopicText';
import { useTheme } from '@/contexts/ThemeContext';
import { useToast } from '@/contexts/ToastContext';
import { BOTTOM_THRESHOLD } from '@/hooks/bible/use-fab-visibility';
import { useTopicById, useTopicReferences } from '@/src/api';
import { fontSizes, fontWeights, type getColors, lineHeights, spacing } from '@/theme/tokens';
import type { ContentTabType } from '@/types/bible';

/**
 * Convert a number to Unicode superscript characters
 * Maps each digit to its Unicode superscript equivalent
 */
function toSuperscript(num: number): string {
  const superscriptMap: Record<string, string> = {
    '0': '\u2070',
    '1': '\u00b9',
    '2': '\u00b2',
    '3': '\u00b3',
    '4': '\u2074',
    '5': '\u2075',
    '6': '\u2076',
    '7': '\u2077',
    '8': '\u2078',
    '9': '\u2079',
  };

  return num
    .toString()
    .split('')
    .map((digit) => superscriptMap[digit] || digit)
    .join('');
}

/**
 * Clean up byline explanation markdown to remove redundant verse references.
 *
 * The AI-generated byline content often has the verse reference 3 times:
 * 1. As the ## heading (e.g., "## Matthew 13:38")
 * 2. As a standalone line below the heading (e.g., "(Matthew 13:38)")
 * 3. At the end of the blockquoted verse text (e.g., "> ...verse text (Matthew 13:38)")
 *
 * This function removes the redundant #2 and #3 occurrences.
 */
function cleanupBylineReferences(content: string): string {
  if (!content) return content;

  return (
    content
      // Remove standalone "(Reference)" lines that appear right after ## headings
      .replace(/^(## .+)\n+\(([^)]+)\)\n/gm, '$1\n\n')
      // Remove trailing (Reference) from blockquoted verse text
      .replace(/^(> .+?)\s+\([^)]+\)\s*$/gm, '$1')
  );
}

/**
 * Splits markdown into FlatList-friendly chunks. Prefers `## ` heading
 * boundaries (semantically meaningful); if the content has no `## `
 * headings, falls back to paragraph boundaries (`\n\n`). Returns a
 * single chunk for content with neither, so callers can still feed it
 * to a FlatList safely (it just renders one item with no virtualization
 * benefit, which is the right behavior for short prose).
 *
 * Used to feed FlatList for the topic Insight tabs. Topics span many
 * verses on byline (= many `##` sections), and detailed often has
 * subsection headings — both benefit hugely from virtualization.
 * Summary is usually short prose, so it falls back to paragraphs.
 */
function splitMarkdownForVirtualization(markdown: string): { key: string; body: string }[] {
  if (!markdown) return [];
  const normalized = markdown.replace(/\r\n/g, '\n');
  const hasHeadings = /^## /m.test(normalized);
  let parts: string[];
  if (hasHeadings) {
    // Split at `## ` boundaries, keeping the heading with its body.
    const lines = normalized.split('\n');
    const buf: string[] = [];
    parts = [];
    const flush = () => {
      const body = buf.join('\n').trim();
      if (body.length > 0) parts.push(body);
      buf.length = 0;
    };
    for (const line of lines) {
      if (line.startsWith('## ') && buf.length > 0) flush();
      buf.push(line);
    }
    flush();
  } else {
    // No headings — split at blank lines (paragraph boundaries). Safe
    // because paragraphs are independent markdown blocks. Lists,
    // blockquotes, and code blocks stay within a single paragraph.
    parts = normalized
      .split(/\n{2,}/)
      .map((p) => p.trim())
      .filter((p) => p.length > 0);
  }
  return parts.map((body, idx) => ({ key: `section-${idx}`, body }));
}

/**
 * Preprocess Bible references text to format verse numbers as Unicode superscripts
 */
function formatVerseNumbers(text: string): string {
  if (!text) return text;

  // Match pattern: standalone number on its own line, followed by verse text
  const versePattern = /^(\d+)\n([^\n])/gm;

  return text.replace(versePattern, (_match, verseNum, firstChar) => {
    return `**${toSuperscript(Number.parseInt(verseNum, 10))}**${firstChar}`;
  });
}

/**
 * Custom markdown renderers for special formatting
 */
const markdownRules: RenderRules = {};

/**
 * Props for TopicPage component
 *
 * All props are DYNAMIC - they update when the sliding window shifts.
 * The key is set by the parent based on window position, not content.
 */
export interface TopicPageProps {
  /** Topic UUID - DYNAMIC prop, updates on window shift */
  topicId: string;

  /** Active reading mode tab */
  activeTab: ContentTabType;
  /** Current view mode (bible or explanations) */
  activeView: 'bible' | 'explanations';
  /**
   * Shared visual progress (0 = Bible, 1 = Insight) driven by parent.
   * Optional so isolated callers can omit; falls back to a local
   * sharedValue mirroring activeView. Matches the Bible ChapterPage
   * pattern.
   */
  toggleProgress?: SharedValue<number>;
  /**
   * Shared visual key (active tab) for inner tab switching. Drives each
   * tab's wrapper maxHeight + opacity on the UI thread so the swap is
   * instant. Optional with activeTab-mirroring fallback.
   */
  activeTabProgress?: SharedValue<ContentTabType>;
  /** Whether to reset scroll to top on topic change (default: true) */
  shouldResetScroll?: boolean;
  /** Whether this page is being preloaded (skips heavy AI content) */
  isPreloading?: boolean;
  /** Callback when user scrolls - receives velocity (px/s) and isAtBottom flag */
  onScroll?: (velocity: number, isAtBottom: boolean) => void;
  /** Callback when user taps the screen */
  onTap?: () => void;
  /** Callback when user wants to share current topic */
  onShare?: () => void;
  /** Callback when a verse is pressed */
  onVersePress?: (verseData: VersePress) => void;
}

/**
 * TopicPage Component
 *
 * Renders a single topic within a PagerView page.
 * Component instance stays stable, props update when window shifts.
 *
 * Performance Optimizations:
 * - Wrapped with React.memo to prevent unnecessary re-renders
 * - Only re-renders when topicId, category, activeTab, or activeView changes
 *
 * @example
 * ```tsx
 * // Parent sets stable key based on position
 * <TopicPage
 *   key="page-2"              // STABLE: never changes
 *   topicId="topic-uuid-003"  // DYNAMIC: updates on window shift
 *   category="EVENT"          // DYNAMIC: updates on window shift
 *   activeTab="summary"
 *   activeView="bible"
 * />
 * ```
 */
export function TopicPage({
  topicId,
  activeTab,
  activeView,
  toggleProgress,
  activeTabProgress,
  shouldResetScroll = true,
  isPreloading = false,
  onScroll,
  onTap,
  onShare,
  onVersePress,
}: TopicPageProps) {
  const { colors } = useTheme();
  // Memoise the StyleSheet objects so they're stable across renders. The
  // raw `createStyles(colors)` call returns fresh objects every time,
  // which breaks any Markdown component's prop-equality check downstream
  // and forces it to re-parse the entire markdown string on every render.
  const { styles, markdownStyles } = useMemo(() => createStyles(colors), [colors]);
  const { showToast } = useToast();

  // TODO: Implement Bible version selection in Settings page
  // For now, hardcoded to NASB1995 (backend default)
  const bibleVersion = 'NASB1995';

  // Word definition tooltip state (long-press dictionary lookup)
  const [wordToDefine, setWordToDefine] = useState<{
    word: string;
    verseNumber: number;
  } | null>(null);
  const [wordDefinitionVisible, setWordDefinitionVisible] = useState(false);

  const handleWordSelect = useCallback((selection: WordSelection, clearSelection: () => void) => {
    setWordToDefine({ word: selection.word, verseNumber: selection.verseNumber });
    setWordDefinitionVisible(true);
    clearSelection();
  }, []);

  const handleWordDefinitionClose = useCallback(() => {
    setWordDefinitionVisible(false);
    setWordToDefine(null);
  }, []);

  const handleWordDefinitionCopy = useCallback(() => {
    showToast('Copied to clipboard');
  }, [showToast]);

  // Markdown text rule that wraps text nodes with HighlightedText for word
  // long-press dictionary lookup (used in the Explanations view markdown).
  const dictionaryMarkdownRules: RenderRules = useMemo(
    () => ({
      ...markdownRules,
      text: (node, _children, _parent, styles, inheritedStyles = {}) => (
        <HighlightedText
          key={node.key}
          text={node.content}
          verseNumber={0}
          style={[inheritedStyles, styles.text]}
          onWordSelect={handleWordSelect}
          isVisible={true}
        />
      ),
    }),
    [handleWordSelect]
  );

  // Track last scroll position and timestamp for velocity calculation
  const lastScrollY = useRef(0);
  const lastScrollTime = useRef(Date.now());

  // Track touch start time and position to differentiate tap from scroll
  const touchStartTime = useRef(0);
  const touchStartY = useRef(0);

  // Pre-warmed flag mirrors Bible's ChapterPage pattern: fires as soon
  // as the initial interaction settles (~16ms after mount) so the
  // Insight subtree mounts before the user first taps Bible/Insight.
  // Sticky once true; resets when topicId shifts so each new active
  // topic gets its own prewarm.
  const [insightPrewarmed, setInsightPrewarmed] = useState(false);

  // Visit-based lazy mount for the inner tabs (summary/byline/detailed).
  // Only the currently-active tab mounts on initial topic render; other
  // tabs mount when the user actually taps them. Once a tab is visited
  // it stays mounted — subsequent switches are instant via sharedValue
  // opacity flip. Resets on topicId change.
  //
  // Replaces the previous staggered-timer mount that auto-mounted every
  // tab within 2.1s of topic settle. That timer blocked the JS thread
  // parsing markdown for tabs the user wasn't even looking at, which
  // was the cause of the 3-5s "load" lag after swiping to a new topic
  // while on the byline tab (even though byline itself is now
  // virtualized).
  const [visitedTabs, setVisitedTabs] = useState<Set<ContentTabType>>(() => new Set([activeTab]));

  // Reset visitedTabs on topicId change so each new topic starts with
  // only the currently-active tab mounted (others stay lazy). DON'T
  // reset insightPrewarmed — once true, keep it sticky. The data inside
  // (markdown memos) refreshes via useTopicById + bylineSections deps,
  // so unmount/remount is unnecessary and causes a flicker on every
  // topic swipe ("byline loads, flickers, loads again").
  // biome-ignore lint/correctness/useExhaustiveDependencies: intentional reset on topicId change
  useEffect(() => {
    setVisitedTabs(new Set([activeTab]));
  }, [topicId]);

  // Add the active tab to the visited set whenever it changes.
  useEffect(() => {
    setVisitedTabs((prev) => {
      if (prev.has(activeTab)) return prev;
      const next = new Set(prev);
      next.add(activeTab);
      return next;
    });
  }, [activeTab]);

  // Prewarm fires for buffer pages too — not gated on isPreloading.
  // Each instance mounts its Insight subtree (with only the active
  // tab's content per visitedTabs) so the next swipe lands on a page
  // that already has content rendered, no blank-frame gap. Cost is
  // small because each buffer only parses one tab's markdown (and
  // byline is virtualized to ~3 sections).
  useEffect(() => {
    if (insightPrewarmed) return;
    const handle = InteractionManager.runAfterInteractions(() => {
      setInsightPrewarmed(true);
    });
    return () => {
      handle.cancel();
    };
  }, [insightPrewarmed]);

  // Reset scroll state when topic changes. Separate refs per inner tab
  // matches Bible's pattern and keeps each tab's scroll position
  // independent across switches.
  const bibleScrollRef = useRef<ScrollView>(null);
  // All three Insight tabs are FlatLists now — use scrollToOffset.
  const summaryScrollRef = useRef<FlatList<{ key: string; body: string }>>(null);
  const bylineScrollRef = useRef<FlatList<{ key: string; body: string }>>(null);
  const detailedScrollRef = useRef<FlatList<{ key: string; body: string }>>(null);

  // biome-ignore lint/correctness/useExhaustiveDependencies: topicId and shouldResetScroll are required to trigger scroll reset
  useEffect(() => {
    // Reset scroll position to top when topicId changes
    // This prevents "height teleportation" from previous topic
    // ONLY if shouldResetScroll is true (skipped during seamless pager snaps)
    if (shouldResetScroll) {
      bibleScrollRef.current?.scrollTo({ y: 0, animated: false });
      summaryScrollRef.current?.scrollToOffset({ offset: 0, animated: false });
      bylineScrollRef.current?.scrollToOffset({ offset: 0, animated: false });
      detailedScrollRef.current?.scrollToOffset({ offset: 0, animated: false });
    }

    // Reset internal scroll tracking
    lastScrollY.current = 0;
  }, [topicId, shouldResetScroll]);

  // Fetch topic data with verse replacement
  const { data: topicData, isLoading: isTopicLoading } = useTopicById(topicId, bibleVersion);
  const { data: references } = useTopicReferences(topicId);

  // Keep references to last valid data to prevent flicker during transitions
  // biome-ignore lint/suspicious/noExplicitAny: Hybrid data structure
  const lastTopicDataRef = useRef<any | null>(null);
  const lastReferencesRef = useRef<typeof references | null>(null);

  if (topicData) lastTopicDataRef.current = topicData;
  if (references) lastReferencesRef.current = references;

  // biome-ignore lint/suspicious/noExplicitAny: Hybrid data structure
  const displayTopicData = (topicData || lastTopicDataRef.current) as any;
  const displayReferences = references || lastReferencesRef.current;

  /**
   * Handle touch start - record time and position
   */
  const handleTouchStart = (event: GestureResponderEvent) => {
    touchStartTime.current = Date.now();
    touchStartY.current = event.nativeEvent.pageY;
  };

  /**
   * Handle touch end - detect if it was a tap (not a scroll)
   * A tap is defined as:
   * - Touch duration < 200ms
   * - Movement < 10 pixels
   */
  const handleTouchEnd = (event: GestureResponderEvent) => {
    if (!onTap) return;

    const touchDuration = Date.now() - touchStartTime.current;
    const touchMovement = Math.abs(event.nativeEvent.pageY - touchStartY.current);

    // Only trigger tap if it was quick and didn't move much
    if (touchDuration < 200 && touchMovement < 10) {
      onTap();
    }
  };

  /**
   * Handle scroll events - calculate velocity and detect bottom
   */
  const handleScroll = (event: NativeSyntheticEvent<NativeScrollEvent>) => {
    if (!onScroll) return;

    const { contentOffset, contentSize, layoutMeasurement } = event.nativeEvent;
    const currentScrollY = contentOffset.y;
    const currentTime = Date.now();

    // Calculate scroll velocity (pixels per second)
    const timeDelta = currentTime - lastScrollTime.current;
    const scrollDelta = currentScrollY - lastScrollY.current; // Signed value to track direction
    const velocity = timeDelta > 0 ? (scrollDelta / timeDelta) * 1000 : 0;

    // Check if at bottom
    const scrollHeight = contentSize.height - layoutMeasurement.height;
    const isAtBottom = scrollHeight - currentScrollY <= BOTTOM_THRESHOLD;

    // Update refs
    lastScrollY.current = currentScrollY;
    lastScrollTime.current = currentTime;

    // Call parent callback
    onScroll(velocity, isAtBottom);
  };

  // Type guard for topic
  const topic =
    displayTopicData?.topic &&
    typeof displayTopicData.topic === 'object' &&
    'name' in displayTopicData.topic
      ? (displayTopicData.topic as {
          name: string;
          description?: string;
          topic_id: string;
          category: string;
        })
      : null;

  // Safely extract description as string
  const topicDescription: string | null =
    topic && typeof topic.description === 'string' && topic.description.trim()
      ? topic.description
      : null;

  // UI-thread driven opacities — flip the visible content the same frame
  // as the tap, without waiting for the activeView prop reconciliation.
  // Falls back to a local sharedValue mirroring activeView when no parent
  // sharedValue is provided (tests, isolated callers).
  const localToggleProgress = useSharedValue(activeView === 'bible' ? 0 : 1);
  useEffect(() => {
    if (toggleProgress) return;
    localToggleProgress.value = withTiming(activeView === 'bible' ? 0 : 1, {
      duration: 180,
      easing: Easing.out(Easing.cubic),
    });
  }, [activeView, localToggleProgress, toggleProgress]);
  const effectiveProgress = toggleProgress ?? localToggleProgress;
  const insightContainerStyle = useAnimatedStyle(() => {
    'worklet';
    return {
      opacity: effectiveProgress.value,
      zIndex: effectiveProgress.value > 0.5 ? 1 : 0,
    };
  });
  const bibleContainerStyle = useAnimatedStyle(() => {
    'worklet';
    return {
      opacity: 1 - effectiveProgress.value,
      zIndex: effectiveProgress.value > 0.5 ? 0 : 1,
    };
  });

  // Pre-process + memoise each tab's rendered markdown JSX. Without this,
  // every tab tap triggers TopicPage to re-render with the same content,
  // and react-native-markdown-display re-parses ALL three trees from
  // scratch (the inline `.replace()` calls produce fresh string refs each
  // render, and the markdown component can't tell it's the same input).
  // Logs showed 3-5s of JS-thread blocking per tap before this memo.
  // All three Insight tabs feed FlatLists so virtualization can keep
  // the first-tap parse small. Splitter prefers `## ` headings;
  // falls back to paragraph boundaries when there are none (typical
  // for summary).
  const summarySections = useMemo<{ key: string; body: string }[]>(() => {
    const raw = displayTopicData?.explanation?.summary;
    if (typeof raw !== 'string' || !raw) return [];
    const processed = raw.replace(/#{1,6}\s*Summary\s*\n/gi, '\n');
    return splitMarkdownForVirtualization(processed);
  }, [displayTopicData?.explanation?.summary]);

  const bylineSections = useMemo<{ key: string; body: string }[]>(() => {
    const raw = displayTopicData?.explanation?.byline;
    if (typeof raw !== 'string' || !raw) return [];
    const processed = cleanupBylineReferences(raw).replace(/#{1,6}\s*Summary\s*\n/gi, '\n');
    return splitMarkdownForVirtualization(processed);
  }, [displayTopicData?.explanation?.byline]);

  const detailedSections = useMemo<{ key: string; body: string }[]>(() => {
    const raw = displayTopicData?.explanation?.detailed;
    if (typeof raw !== 'string' || !raw) return [];
    const processed = raw.replace(/#{1,6}\s*Summary\s*\n/gi, '\n');
    return splitMarkdownForVirtualization(processed);
  }, [displayTopicData?.explanation?.detailed]);

  // One render function shared across all three tabs — same Markdown
  // component, same rules, same styles per section.
  const renderMarkdownSection = useCallback(
    ({ item }: { item: { key: string; body: string } }) => (
      <Markdown style={markdownStyles} rules={dictionaryMarkdownRules}>
        {item.body}
      </Markdown>
    ),
    [markdownStyles, dictionaryMarkdownRules]
  );
  const sectionKeyExtractor = useCallback((item: { key: string; body: string }) => item.key, []);

  // Inner-tab visibility — driven by activeTabProgress. Each tab is now
  // its own absolute-positioned ScrollView (Bible pattern); only opacity
  // and zIndex flip on the UI thread, no layout reflow. The previous
  // maxHeight-collapse approach inside a shared ScrollView forced Yoga
  // to re-measure the entire markdown subtree on every tab switch and
  // was the root cause of the sloppy/teleport animations.
  const localActiveTabProgress = useSharedValue<ContentTabType>(activeTab);
  useEffect(() => {
    if (activeTabProgress) return;
    localActiveTabProgress.value = activeTab;
  }, [activeTab, localActiveTabProgress, activeTabProgress]);
  const effectiveTabProgress = activeTabProgress ?? localActiveTabProgress;
  const summaryTabAnimStyle = useAnimatedStyle(() => {
    'worklet';
    const match = effectiveTabProgress.value === 'summary';
    return { opacity: match ? 1 : 0, zIndex: match ? 1 : 0 };
  });
  const bylineTabAnimStyle = useAnimatedStyle(() => {
    'worklet';
    const match = effectiveTabProgress.value === 'byline';
    return { opacity: match ? 1 : 0, zIndex: match ? 1 : 0 };
  });
  const detailedTabAnimStyle = useAnimatedStyle(() => {
    'worklet';
    const match = effectiveTabProgress.value === 'detailed';
    return { opacity: match ? 1 : 0, zIndex: match ? 1 : 0 };
  });

  // Loading state - show skeleton ONLY on initial mount when no data exists
  if (isTopicLoading && !displayTopicData) {
    return (
      <View style={styles.container} testID={`topic-page-${topicId}`}>
        <ScrollView
          style={styles.container}
          contentContainerStyle={styles.contentContainer}
          testID={`topic-page-scroll-${topicId}`}
        >
          <SkeletonLoader />
        </ScrollView>
      </View>
    );
  }

  // Error or no data state
  if (!topic && !isTopicLoading) {
    return (
      <View style={styles.container} testID={`topic-page-${topicId}`}>
        <ScrollView
          style={styles.container}
          contentContainerStyle={styles.contentContainer}
          testID={`topic-page-scroll-${topicId}`}
        >
          <View style={styles.emptyContainer}>
            <Text style={styles.emptyText}>Topic not available</Text>
          </View>
        </ScrollView>
      </View>
    );
  }

  return (
    <View style={styles.container} testID={`topic-page-${topicId}`}>
      {/* Bible References View — opacity flipped by toggleProgress on
          the UI thread. Always absolute-fill so it overlaps the Insight
          container at the same bounds; opacity decides which is visible. */}
      <Animated.ScrollView
        ref={bibleScrollRef as React.Ref<Animated.ScrollView>}
        style={[styles.container, styles.absoluteFill, bibleContainerStyle]}
        contentContainerStyle={styles.contentContainer}
        showsVerticalScrollIndicator={true}
        testID={`topic-page-scroll-${topicId}-bible`}
        onScroll={handleScroll}
        scrollEventThrottle={16}
        onTouchStart={handleTouchStart}
        onTouchEnd={handleTouchEnd}
        pointerEvents={activeView === 'bible' ? 'auto' : 'none'}
      >
        {displayReferences &&
        typeof displayReferences === 'object' &&
        'content' in displayReferences &&
        typeof displayReferences.content === 'string' ? (
          // Use TopicText if content has structured format (## subtitles)
          // Otherwise fall back to existing Markdown renderer
          displayReferences.content.includes('## ') ? (
            <TopicText
              topicName={topic?.name || ''}
              markdownContent={displayReferences.content}
              onShare={onShare}
              onVersePress={onVersePress}
              onWordSelect={handleWordSelect}
            />
          ) : (
            <>
              {/* Topic Title Row with Share button */}
              <View style={styles.titleRow}>
                <Text style={styles.topicTitle} accessibilityRole="header">
                  {topic?.name}
                </Text>
                {onShare && (
                  <View style={styles.iconButtons}>
                    <ShareButton onShare={onShare} />
                  </View>
                )}
              </View>

              {/* Topic Description */}
              {topicDescription ? (
                <Text style={styles.topicDescription}>{topicDescription}</Text>
              ) : null}

              <View style={styles.referencesContainer}>
                <Markdown style={markdownStyles} rules={markdownRules}>
                  {
                    // First format verse numbers, THEN process newlines
                    formatVerseNumbers(displayReferences.content)
                      .replace(/\n\n/g, '___PARAGRAPH___')
                      .replace(/\n/g, ' ')
                      .replace(/___PARAGRAPH___/g, '\n\n')
                  }
                </Markdown>
              </View>
            </>
          )
        ) : (
          <>
            {/* Topic Title Row with Share button */}
            <View style={styles.titleRow}>
              <Text style={styles.topicTitle} accessibilityRole="header">
                {topic?.name}
              </Text>
              {onShare && (
                <View style={styles.iconButtons}>
                  <ShareButton onShare={onShare} />
                </View>
              )}
            </View>

            {/* Topic Description */}
            {topicDescription ? (
              <Text style={styles.topicDescription}>{topicDescription}</Text>
            ) : null}

            <View style={styles.emptyContainer}>
              <Text style={styles.emptyText}>No Bible references available for this topic.</Text>
            </View>
          </>
        )}
        <BottomLogo />
      </Animated.ScrollView>

      {/* Explanations View — opacity flipped by toggleProgress on the UI
          thread. Always absolute-fill, overlapping Bible at the same
          bounds. Mount gated on insightPrewarmed OR the legacy stage
          tick — both only fire on the ACTIVE page (isPreloading=false),
          so buffer pages skip the heavy markdown parse entirely.
          Previously the `activeView === 'explanations'` condition
          forced buffer pages to render the Insight subtree on every
          swipe, producing 3+ second render blocks. */}
      {/* Insight view — matches Bible ChapterPage's absolute-overlap
          pattern. Each inner tab gets its own ScrollView, absolute-
          positioned and overlapping at the same bounds. Switching tabs
          is pure opacity flip on the UI thread via activeTabProgress —
          no layout reflow (which was the source of the sloppy/teleport
          animations under the previous maxHeight-collapse design). */}
      {insightPrewarmed && (
        <Animated.View
          style={[styles.container, styles.absoluteFill, insightContainerStyle]}
          pointerEvents={activeView === 'explanations' ? 'auto' : 'none'}
        >
          {visitedTabs.has('summary') && (
            <Animated.View
              style={[styles.absoluteFill, summaryTabAnimStyle]}
              testID="topic-explanation-summary"
              pointerEvents={activeTab === 'summary' ? 'auto' : 'none'}
            >
              {summarySections.length > 0 ? (
                <FlatList
                  ref={summaryScrollRef}
                  style={styles.container}
                  contentContainerStyle={styles.contentContainer}
                  data={summarySections}
                  keyExtractor={sectionKeyExtractor}
                  renderItem={renderMarkdownSection}
                  showsVerticalScrollIndicator={true}
                  testID={`topic-page-scroll-${topicId}-summary`}
                  onScroll={activeTab === 'summary' ? handleScroll : undefined}
                  scrollEventThrottle={16}
                  onTouchStart={handleTouchStart}
                  onTouchEnd={handleTouchEnd}
                  initialNumToRender={3}
                  maxToRenderPerBatch={2}
                  windowSize={5}
                  removeClippedSubviews
                />
              ) : (
                <View style={styles.emptyContainer}>
                  <Text style={styles.emptyText}>
                    No summary explanation available for this topic yet.
                  </Text>
                </View>
              )}
            </Animated.View>
          )}

          {visitedTabs.has('byline') && (
            <Animated.View
              style={[styles.absoluteFill, bylineTabAnimStyle]}
              testID="topic-explanation-byline"
              pointerEvents={activeTab === 'byline' ? 'auto' : 'none'}
            >
              {bylineSections.length > 0 ? (
                <FlatList
                  ref={bylineScrollRef}
                  style={styles.container}
                  contentContainerStyle={styles.contentContainer}
                  data={bylineSections}
                  keyExtractor={sectionKeyExtractor}
                  renderItem={renderMarkdownSection}
                  showsVerticalScrollIndicator={true}
                  testID={`topic-page-scroll-${topicId}-byline`}
                  onScroll={activeTab === 'byline' ? handleScroll : undefined}
                  scrollEventThrottle={16}
                  onTouchStart={handleTouchStart}
                  onTouchEnd={handleTouchEnd}
                  // Render only enough sections to fill the screen on first
                  // mount; load more as the user scrolls. Topics with 30+
                  // verses used to block ~3-5s on first byline tap; now it
                  // renders the first ~3 sections instantly and streams
                  // the rest in during scroll.
                  initialNumToRender={3}
                  maxToRenderPerBatch={2}
                  windowSize={5}
                  removeClippedSubviews
                />
              ) : (
                <View style={styles.emptyContainer}>
                  <Text style={styles.emptyText}>
                    No byline explanation available for this topic yet.
                  </Text>
                </View>
              )}
            </Animated.View>
          )}

          {visitedTabs.has('detailed') && (
            <Animated.View
              style={[styles.absoluteFill, detailedTabAnimStyle]}
              testID="topic-explanation-detailed"
              pointerEvents={activeTab === 'detailed' ? 'auto' : 'none'}
            >
              {detailedSections.length > 0 ? (
                <FlatList
                  ref={detailedScrollRef}
                  style={styles.container}
                  contentContainerStyle={styles.contentContainer}
                  data={detailedSections}
                  keyExtractor={sectionKeyExtractor}
                  renderItem={renderMarkdownSection}
                  showsVerticalScrollIndicator={true}
                  testID={`topic-page-scroll-${topicId}-detailed`}
                  onScroll={activeTab === 'detailed' ? handleScroll : undefined}
                  scrollEventThrottle={16}
                  onTouchStart={handleTouchStart}
                  onTouchEnd={handleTouchEnd}
                  initialNumToRender={3}
                  maxToRenderPerBatch={2}
                  windowSize={5}
                  removeClippedSubviews
                />
              ) : (
                <View style={styles.emptyContainer}>
                  <Text style={styles.emptyText}>
                    No detailed explanation available for this topic yet.
                  </Text>
                </View>
              )}
            </Animated.View>
          )}
        </Animated.View>
      )}

      {/* Word Definition Tooltip — dictionary lookup on long-press */}
      {wordToDefine && (
        <WordDefinitionTooltip
          visible={wordDefinitionVisible}
          word={wordToDefine.word}
          bookName={topic?.name || ''}
          chapterNumber={0}
          verseNumber={wordToDefine.verseNumber}
          onClose={handleWordDefinitionClose}
          onCopy={handleWordDefinitionCopy}
        />
      )}
    </View>
  );
}

/**
 * Creates all styles for TopicPage component
 * Returns both component styles and markdown styles in a single factory
 */
const createStyles = (colors: ReturnType<typeof getColors>) => {
  const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    absoluteFill: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    contentContainer: {
      flexGrow: 1,
      paddingHorizontal: spacing.lg,
      paddingVertical: spacing.xxl,
      // Add bottom padding to account for floating action buttons
      paddingBottom: 60,
    },
    titleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: spacing.xxl,
    },
    topicTitle: {
      flex: 1,
      fontSize: fontSizes.displayMedium,
      fontWeight: fontWeights.bold,
      lineHeight: fontSizes.displayMedium * lineHeights.display,
      color: colors.textPrimary,
      marginRight: spacing.md,
    },
    iconButtons: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.xs,
    },
    topicDescription: {
      fontSize: fontSizes.body,
      lineHeight: fontSizes.body * lineHeights.body,
      color: colors.textSecondary,
      marginBottom: spacing.xxl,
    },
    referencesContainer: {
      marginBottom: spacing.xxxl,
    },
    explanationContainer: {
      marginTop: spacing.xxl,
      paddingTop: spacing.xxl,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    emptyContainer: {
      padding: spacing.xxl,
      alignItems: 'center',
    },
    emptyText: {
      fontSize: fontSizes.body,
      color: colors.textSecondary,
      textAlign: 'center',
    },
  });

  /**
   * Markdown Styles
   * Reused from ChapterReader for consistency
   */
  const verseNumberSuperscriptStyle = {
    fontSize: fontSizes.bodyLarge,
    fontWeight: fontWeights.bold,
    color: colors.textTertiary,
    marginRight: spacing.xs / 2,
  };

  const markdownStyles = StyleSheet.create({
    body: {
      fontSize: fontSizes.bodyLarge,
      lineHeight: fontSizes.bodyLarge * 2.0,
      color: colors.textPrimary,
    },
    heading1: {
      fontSize: fontSizes.heading1,
      fontWeight: fontWeights.bold,
      lineHeight: fontSizes.heading1 * lineHeights.heading,
      color: colors.textPrimary,
      marginTop: spacing.xxl,
      marginBottom: spacing.md,
    },
    heading2: {
      fontSize: fontSizes.heading2,
      fontWeight: fontWeights.semibold,
      lineHeight: fontSizes.heading2 * lineHeights.heading,
      color: colors.textPrimary,
      marginTop: 64,
      marginBottom: spacing.sm,
    },
    heading3: {
      fontSize: fontSizes.heading3,
      fontWeight: fontWeights.semibold,
      lineHeight: fontSizes.heading3 * lineHeights.heading,
      color: colors.textPrimary,
      marginTop: 64,
      marginBottom: spacing.sm,
    },
    paragraph: {
      fontSize: fontSizes.bodyLarge,
      lineHeight: fontSizes.bodyLarge * 2.0,
      color: colors.textPrimary,
      marginBottom: spacing.md,
    },
    list_item: {
      fontSize: fontSizes.bodyLarge,
      lineHeight: fontSizes.bodyLarge * 2.0,
      color: colors.textPrimary,
      marginBottom: spacing.xs,
    },
    bullet_list: {
      marginBottom: spacing.md,
    },
    ordered_list: {
      marginBottom: spacing.md,
    },
    strong: {
      // Used for verse numbers
      ...verseNumberSuperscriptStyle,
    },
    em: {
      fontStyle: 'italic',
    },
    blockquote: {
      backgroundColor: colors.backgroundElevated,
      borderLeftWidth: 4,
      borderLeftColor: colors.gold,
      paddingVertical: spacing.md,
      paddingHorizontal: spacing.lg,
      marginVertical: spacing.md,
    },
    verseNumberSuperscript: verseNumberSuperscriptStyle,
  });

  return { styles, markdownStyles };
};
